---
- name: Create node_exporter user
  user:
    name: node_exporter
    system: yes
    shell: /bin/false
    create_home: no

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/latest/download/node_exporter-1.6.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
